[package]
name = "cddl-codegen"
version = "0.1.0"
edition = "2018"

[dependencies]
cbor_event = "2.1.3"
cddl = { git = 'https://github.com/dcSpark/cddl', branch = 'dcSpark-ast-parent-pointer' }
clap = { version = "~3.1.5", features = ["derive"] }
codegen = "0.1.3"
either = "1.5.3"
once_cell = "1.10.0"
nom = "7.1.1"