name: Linter and unit tests

on:
  push:
    branches: [ master ]
    paths:
      - '.github/workflows/build.yml'
      - "**/Cargo.*"
      - "src/**"
      - "tests/**"
  pull_request:
    branches: [ master ]
    paths:
      - '.github/workflows/build.yml'
      - "**/Cargo.*"
      - "src/**"
      - "tests/**"

jobs:
  test:
    name: Rust project
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2

      - name: "Install latest nightly"
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
          components: rustfmt, clippy

      - name: "Format check"
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      - name: "Linter checks"
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --locked --workspace --all-features --all-targets -- --deny "clippy::all"

      - name: "Run cargo build"
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --locked --workspace --all-features --all-targets

      - name: "Run cargo test"
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all-features --all-targets
